Repository bankobotv14/BankoBot, pull requests merged in 2021-01, with the labels that each got.

#7 Feature/search
  src/main/kotlin/de/nycode/bankobot/BankoBot.kt
  src/main/kotlin/de/nycode/bankobot/commands/general/SearchCommand.kt
  src/main/kotlin/de/nycode/bankobot/config/Config.kt
  src/main/kotlin/de/nycode/bankobot/utils/GoogleUtils.kt
  src/main/kotlin/de/nycode/bankobot/utils/LoadingUtil.kt
Labels: enhancement

#9 Feature/jdoodle
  src/main/kotlin/de/nycode/bankobot/command/CodeBlockargument.kt
  src/main/kotlin/de/nycode/bankobot/commands/general/JDoodleCommand.kt
  src/main/kotlin/de/nycode/bankobot/config/Config.kt
  src/main/kotlin/de/nycode/bankobot/utils/CodeBlockUtil.kt
  src/main/kotlin/de/nycode/bankobot/utils/Constants.kt
  src/main/kotlin/de/nycode/bankobot/utils/JDoodleUtil.kt
Labels: enhancement

#12 Make slash commands have their own event handler so they acknowledge preconditions etc.
  src/main/kotlin/de/nycode/bankobot/BankoBot.kt
  src/main/kotlin/de/nycode/bankobot/command/AbstractKordFilter.kt
  src/main/kotlin/de/nycode/bankobot/command/BlacklistEnforcer.kt
  src/main/kotlin/de/nycode/bankobot/command/permissions/PermissionHandler.kt
  src/main/kotlin/de/nycode/bankobot/command/permissions/Permissions.kt
  src/main/kotlin/de/nycode/bankobot/command/slashcommands/InteractionEventHandler.kt
  src/main/kotlin/de/nycode/bankobot/command/slashcommands/Pipeline.kt
  src/main/kotlin/de/nycode/bankobot/command/slashcommands/Prefix.kt
Labels: bug

#15 Feature/example
  .env.example
  README.md
Labels: documentation

#16 Fix eval command
  .idea/compiler.xml
  docker-compose.yml
  src/main/kotlin/de/nycode/bankobot/BankoBot.kt
  src/main/kotlin/de/nycode/bankobot/commands/dev/EvalCommand.kt
  src/main/kotlin/de/nycode/bankobot/config/Config.kt
Labels: bug

#19 Fix production error handler
  src/main/kotlin/de/nycode/bankobot/command/ErrorHandlers.kt
Labels: bug

#22 Remove docsdex submodule
  .gitmodules
  .idea/vcs.xml
Labels: invalid

#23 Fix Error handler for slash commands
  src/main/kotlin/de/nycode/bankobot/command/ErrorHandlers.kt
  src/main/kotlin/de/nycode/bankobot/command/slashcommands/InteractionEventHandler.kt
  src/main/kotlin/de/nycode/bankobot/command/slashcommands/Pipeline.kt
Labels: bug
