Repository bankobotv14/BankoBot, pull requests merged in 2021-02, with the labels that each got.

#30 Fix bugs
  src/main/kotlin/de/nycode/bankobot/commands/general/DocsCommand.kt
  src/main/kotlin/de/nycode/bankobot/commands/general/SearchCommand.kt
  src/main/kotlin/de/nycode/bankobot/commands/tag/commands/SearchTagsCommand.kt
  src/main/kotlin/de/nycode/bankobot/utils/GoogleUtils.kt
Labels: bug

#37 Adds DCommand
  src/main/kotlin/de/nycode/bankobot/commands/general/DCommand.kt
  src/main/kotlin/de/nycode/bankobot/commands/general/DocsCommand.kt
Labels: command, enhancement

#49 Fix docs command bugs
  src/main/kotlin/de/nycode/bankobot/commands/general/DocsCommand.kt
  src/main/kotlin/de/nycode/bankobot/docdex/DocumentedReference.kt
Labels: bug

#51 Fix broken permissions for blacklist
  build.gradle.kts
  src/main/kotlin/de/nycode/bankobot/commands/moderation/BlacklistCommand.kt
Labels: bug

#48 Use MathJS API instead of self parsing
  src/main/kotlin/de/nycode/bankobot/command/MathExpressionArgument.kt
  src/main/kotlin/de/nycode/bankobot/commands/general/CalcCommand.kt
  src/main/kotlin/de/nycode/bankobot/config/Config.kt
  src/main/kotlin/de/nycode/bankobot/variables/Expression.kt
  src/main/kotlin/de/nycode/bankobot/variables/TagVariables.kt
  src/main/kotlin/de/nycode/bankobot/variables/VariableParser.kt
  src/main/kotlin/de/nycode/bankobot/variables/parsers/calc/CalcExpression.kt
  src/main/kotlin/de/nycode/bankobot/variables/parsers/calc/CalcExpressionParser.kt
  src/main/kotlin/de/nycode/bankobot/variables/parsers/calc/CalcExpressionVisitor.kt
  src/main/kotlin/de/nycode/bankobot/variables/parsers/http/HttpExpression.kt
  src/test/kotlin/de/nycode/bankobot/variables/VariableParserTest.kt
  src/test/kotlin/de/nycode/bankobot/variables/parsers/CalcExpressionTest.kt
Labels: enhancement

#52 Fix twitch webhooks
  src/main/kotlin/de/nycode/bankobot/BankoBot.kt
  src/main/kotlin/de/nycode/bankobot/config/Config.kt
  src/main/kotlin/de/nycode/bankobot/twitch/TwitchIntegration.kt
  src/main/kotlin/de/nycode/bankobot/twitch/TwitchSubscription.kt
  src/main/kotlin/de/nycode/bankobot/twitch/WebhookServer.kt
Labels: bug

#57 Make the bot cool
  .idea/compiler.xml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/kotlin/de/nycode/bankobot/command/Extensions.kt
  src/main/kotlin/de/nycode/bankobot/commands/fun/BingBangCommand.kt
  src/main/kotlin/de/nycode/bankobot/commands/general/SourceCommand.kt
Labels: enhancement

#58 Update lavakord to fix bug, causing music to end when user leaves VC
  build.gradle.kts
Labels: bug
